# Generated by Django 5.2.6 on 2025-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('MovieID', models.IntegerField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=180)),
                ('Actor1Name', models.CharField(max_length=85)),
                ('Actor2Name', models.CharField(max_length=85)),
                ('DirectorName', models.CharField(max_length=85)),
                ('MovieGenre', models.CharField(max_length=30)),
                ('ReleaseYear', models.IntegerField()),
            ],
        ),
    ]
